export const TOGGLE_ADDLAYERWINDOW = 'TOGGLE_ADDLAYERWINDOW';
export const SHOW_ADDLAYERWINDOW = 'SHOW_ADDLAYERWINDOW';
export const HIDE_ADDLAYERWINDOW = 'HIDE_ADDLAYERWINDOW';
export const TOGGLE_HELPMODAL = 'TOGGLE_HELPMODAL';
export const SHOW_LAYERTREE = 'SHOW_LAYERTREE';
export const HIDE_LAYERTREE = 'HIDE_LAYERTREE';
