export const SET_START_DATE = 'SET_START_DATE';
export const SET_END_DATE = 'SET_END_DATE';
export const SET_TIME_INTERVAL = 'SET_TIME_INTERVAL';
export const SET_SELECTED_TIME_LAYER = 'SET_SELECTED_TIME_LAYER';
