export const SET_LAYERS = 'SET_LAYERS';
export const ADD_LAYERS = 'ADD_LAYERS';
export const REMOVE_LAYERS = 'REMOVE_LAYERS';
export const CHANGE_LAYER_VISIBILITY = 'CHANGE_LAYER_VISIBILITY';
export const UPDATE_LAYER_ORDERING = 'UPDATE_LAYER_ORDERING';
